AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This CloudFormation template creates a role assumed by CloudFormation during CRUDL operations to
  mutate resources on behalf of the customer.
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ParameterStore
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ssm:*
                Resource: !Sub 'arn:aws:ssm:*:*:parameter/GC/GitSync/*'
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
