AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  SSHGithubURL:
    Type: String
  GitSyncServiceURL:
    Type: String
  GitSyncAccessToken:
    Type: String
  GitSyncAccessSecret:
    Type: String
    NoEcho: True
  GitSyncServiceRole:
    Type: String
    AllowedPattern: '^arn:aws[A-Za-z0-9-]{0,64}:iam:.*:([0-9]{12})?:role/.+$'
Resources:
  # Sync
  GitSyncJobRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: The GitSync Job Repository is synced here
      RepositoryName: GitSyncJobRepository
  GitSyncJobRepositoryAccessRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref GitSyncServiceRole
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GitSyncJobRepositoryAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource:
                  - !Sub '${GitSyncJobRepository.Arn}'
  GitSyncJobRepositoryJob:
    Type: GC::GitSync::Job
    Properties:
      Description: This job sync the GitSyncJob repository to CodeCommit
      GitSyncServiceURL: !Ref GitSyncServiceURL
      GitSyncAccessToken: !Ref GitSyncAccessToken
      GitSyncAccessSecret: !Ref GitSyncAccessSecret
      Repository: !Ref SSHGithubURL
      RepositoryType: GITHUB
      CodeCommitRepository: !Sub 'codecommit::${AWS::Region}://${GitSyncJobRepository.Name}'
      CodeCommitAccessRoleArn: !Sub '${GitSyncJobRepositoryAccessRole.Arn}'
  # Pipeline
  GitSyncJobBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GitSyncJobRepositoryAccess
          PolicyDocument:
            Statement:
              # This should be changed if this code is being copied
              - Effect: Allow
                Action: "*"
                Resource: "*"
  GitSyncJobArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  GitSyncJobCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Packaging: NONE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !Ref GitSyncJobBuildRole
      Source:
        Type: CODEPIPELINE
        InsecureSsl: false
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 14
                python: 3.8
              commands:
                - set -e
                - pip3 install cloudformation-cli
                - pip3 install cloudformation-cli-typescript-plugin
            build:
              commands:
                - set -e
                - sam --version
                - aws --version
                - docker --version
                - cfn --version
                - export GIT_TAG=$(git describe --tags --abbrev=1)
                - ls -la
                - npm install
                - npm install -g typescript
                - tsc
                - echo "Deploying ${GIT_TAG}..."
                - cfn submit --set-default
      TimeoutInMinutes: 30
  GitSyncJobCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RestartExecutionOnUpdate: false
      RoleArn: !Sub '${GitSyncJobBuildRole.Arn}'
      ArtifactStore:
        Type: S3
        Location: !Ref GitSyncJobArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: !Sub '${GitSyncJobRepository.Name}'
                BranchName: master
                PollForSourceChanges: false
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              InputArtifacts: []
              OutputArtifacts:
                - Name: source
        - Name: Main
          Actions:
            - Name: Main
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref GitSyncJobCodeBuild
                PrimarySource: source
              InputArtifacts:
                - Name: source
              OutputArtifacts: []
  # Trigger
  GitSyncJobCodePipelineTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: pipeline-execution
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${GitSyncJobCodePipeline}'
  GitSyncJobCodePipelineTrigger:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources:
          - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${GitSyncJobRepository.Name}'
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - master
      Targets:
        - Arn: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${GitSyncJobCodePipeline}'
          RoleArn: !Sub '${GitSyncJobCodePipelineTriggerRole.Arn}'
          Id: gitsyncjob-codepipeline-trigger
Outputs:
  CodeCommitRepository:
    Value: !Sub 'codecommit::${AWS::Region}://${GitSyncJobRepository.Name}'
  JobID:
    Value: !Sub '${GitSyncJobRepositoryJob.JobID}'
  DeployKey:
    Value: !Sub '${GitSyncJobRepositoryJob.DeployKey}'
  WebhookURL:
    Value: !Sub '${GitSyncJobRepositoryJob.WebhookURL}'
  WebhookSecret:
    Value: !Sub '${GitSyncJobRepositoryJob.WebhookSecret}'
  SyncStatusURL:
    Value: !Sub '${GitSyncJobRepositoryJob.SyncStatusURL}'
