AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  GitSyncServiceURL:
    Type: String
  GitSyncAccessToken:
    Type: String
  GitSyncAccessSecret:
    Type: String
    NoEcho: True
  GitSyncServiceRole:
    Type: String
    AllowedPattern: "^arn:aws[A-Za-z0-9-]{0,64}:iam:.*:([0-9]{12})?:role/.+$"
Resources:
  GitSyncJobRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: The GitSync Job Repository is synced here
      RepositoryName: GitSyncJobRepository
  GitSyncJobRepositoryAccessRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref GitSyncServiceRole
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: GitSyncJobRepositoryAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "*"
                Resource:
                  - !Sub '${GitSyncJobRepository.Arn}'
  GitSyncJobRepositoryJob:
    Type: GC::GitSync::Job
    Properties:
      Description: This job sync the GitSyncJob repository to CodeCommit
      GitSyncServiceURL: !Ref GitSyncServiceURL
      GitSyncAccessToken: !Ref GitSyncAccessToken
      GitSyncAccessSecret: !Ref GitSyncAccessSecret
      Repository: git@github.com:attila-varga-gc/gitsync.git
      RepositoryType: GITHUB
      CodeCommitRepository: !Sub 'codecommit::${AWS::Region}://${GitSyncJobRepository.Name}'
      CodeCommitAccessRoleArn: !Sub '${GitSyncJobRepositoryAccessRole.Arn}'
Outputs:
  CodeCommitRepository:
    Value: !Sub 'codecommit::${AWS::Region}://${GitSyncJobRepository.Name}'
  JobID:
    Value: !Sub '${GitSyncJobRepositoryJob.JobID}'
  DeployKey:
    Value: !Sub '${GitSyncJobRepositoryJob.DeployKey}'
  WebhookURL:
    Value: !Sub '${GitSyncJobRepositoryJob.WebhookURL}'
  WebhookSecret:
    Value: !Sub '${GitSyncJobRepositoryJob.WebhookSecret}'
